name: CI

on:
  push:
    branches:
      - main

jobs:
  g8Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-java@v2
      - name: g8Test
        run: sbt g8Test
